"use client";

import { useState } from "react";

const examples = ["Which truck had the worst fuel efficiency this month?", "Which trucks had detected events this month?", "What happened with TR-07?"];

export default function FleetQueryBox() {
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [tools, setTools] = useState<string[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(value = question) { if (!value.trim() || loading) return; setQuestion(value); setLoading(true); setError(""); setAnswer(""); setTools([]); try { const response = await fetch("/api/query", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: value }) }); const payload = await response.json() as { answer?: string; calledTools?: string[]; error?: string }; if (!response.ok) throw new Error(payload.error); setAnswer(payload.answer ?? "No answer returned."); setTools(payload.calledTools ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to answer the question."); } finally { setLoading(false); } }
  return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-sm font-medium text-sky-300">Ask TankGuard</p><form className="mt-2 flex gap-2" onSubmit={(event) => { event.preventDefault(); void submit(); }}><input disabled={loading} value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about your fleet…" className="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-sky-400 disabled:opacity-60"/><button disabled={loading} className="rounded-lg bg-sky-500 px-3 py-2 text-sm font-medium text-slate-950 disabled:opacity-60">{loading ? "Checking…" : "Ask"}</button></form><div className="mt-2 flex flex-wrap gap-1">{examples.map((example) => <button disabled={loading} key={example} onClick={() => void submit(example)} className="rounded-md bg-slate-800 px-2 py-1 text-left text-xs text-slate-300 hover:bg-slate-700 disabled:opacity-60">{example}</button>)}</div>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}{answer && <div className="mt-3 max-h-44 overflow-y-auto rounded-lg bg-slate-950 p-3 text-sm leading-6 text-slate-200"><p>{answer}</p>{tools.length > 0 && <p className="mt-2 text-xs text-slate-500">checked: {tools.join(", ")}</p>}</div>}</section>;
}
